[book]
title = "Zeebe 中英文档"
description = "Zeebe is an orchestration engine for distributed microservices(Zeebe 是一个用于微服务编排的工作流编排引擎)"

[preprocessor.commit-hash]
command = "./preprocessors/commit-hash.py"

[output.html]
additional-css = ["custom.css"]
additional-js = ["highlight.protobuf.js"]
git-repository-url = "https://github.com/bingohuang/zeebe-docs-zh"

[output.html.fold]
enable = true
level = 0

[output.linkcheck]
exclude = [ "localhost" ]

# enable the following line to check external links, this will increase
# the build time
#follow-web-links = true
